<?php
require_role(['admin']);
require_once __DIR__.'/../controllers/AdminController.php';
$adminCtrl=new AdminController($conn);
$totalUsers=(int)$conn->query('SELECT COUNT(*) total FROM users')->fetch_assoc()['total'];
$totalMhs=(int)$conn->query("SELECT COUNT(*) total FROM users WHERE role='mahasiswa'")->fetch_assoc()['total'];
$totalDosen=(int)$conn->query("SELECT COUNT(*) total FROM users WHERE role='dosen'")->fetch_assoc()['total'];
$totalBimbingan=(int)$conn->query('SELECT COUNT(*) total FROM bimbingan')->fetch_assoc()['total'];
$totalReview=(int)$conn->query("SELECT COUNT(*) total FROM bab_skripsi WHERE status='menunggu_review'")->fetch_assoc()['total'];
$totalSeminar=(int)$conn->query("SELECT COUNT(*) total FROM jadwal_seminar WHERE status IN ('terjadwal','berlangsung')")->fetch_assoc()['total'];
$users=$adminCtrl->getUsers();$dosen=$adminCtrl->getDosen();$bimbingan=$adminCtrl->getBimbingan();
?>
<div class="page-head"><div><h1>Dashboard Admin</h1><p class="muted">Kelola pengguna, pembimbing, dan proses skripsi.</p></div></div>
<div class="card" style="margin-bottom:18px"><strong>Menu Admin</strong><div style="margin-top:10px"><a class="btn btn-primary" href="?page=seminar">Kelola Seminar / Sidang</a></div></div>
<div class="stats-grid"><div class="stat-card"><strong><?=$totalUsers?></strong><span>Total User</span></div><div class="stat-card"><strong><?=$totalMhs?></strong><span>Mahasiswa</span></div><div class="stat-card"><strong><?=$totalDosen?></strong><span>Dosen</span></div><div class="stat-card"><strong><?=$totalBimbingan?></strong><span>Bimbingan</span></div><div class="stat-card"><strong><?=$totalReview?></strong><span>Bab Menunggu Review</span></div><div class="stat-card"><strong><?=$totalSeminar?></strong><span>Jadwal Aktif</span></div></div>
<div class="card"><h2>Manajemen Bimbingan</h2><?php if(!$bimbingan): ?><p class="muted">Belum ada data bimbingan.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Mahasiswa</th><th>Judul</th><th>Pembimbing</th><th>Progress</th><th>Status</th></tr></thead><tbody><?php foreach($bimbingan as $b):$progress=min(100,(int)$b['bab_disetujui']*20); ?><tr><td><?=e($b['mahasiswa_nama'])?></td><td><a href="?page=bimbingan-detail&id=<?=e($b['id'])?>"><?=e($b['judul_skripsi'])?></a></td><td><form method="post" class="inline-form"><input type="hidden" name="action" value="admin_assign_dosen"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="bimbingan_id" value="<?=e($b['id'])?>"><select name="dosen_id" onchange="this.form.submit()"><option value="">Pilih dosen</option><?php foreach($dosen as $d): ?><option value="<?=$d['id']?>" <?=((int)$d['id']===(int)$b['dosen_id']?'selected':'')?>><?=e($d['nama_lengkap'])?></option><?php endforeach; ?></select></form></td><td><?=$progress?>%</td><td><?=getStatusBadge($b['status'])?><form method="post" class="inline-form" style="margin-top:6px"><input type="hidden" name="action" value="admin_bimbingan_status"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="bimbingan_id" value="<?=e($b['id'])?>"><select name="status" onchange="this.form.submit()"><?php foreach(['aktif','ditangguhkan','selesai'] as $st): ?><option value="<?=$st?>" <?=($b['status']===$st?'selected':'')?>><?=e(ucfirst($st))?></option><?php endforeach; ?></select></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<div class="card"><h2>Pengguna</h2><div class="table-wrap"><table><thead><tr><th>Nama</th><th>Username</th><th>Email</th><th>Role</th><th>Terdaftar</th></tr></thead><tbody><?php foreach($users as $u): ?><tr><td><?=e($u['nama_lengkap'])?></td><td><?=e($u['username'])?></td><td><?=e($u['email'])?></td><td><?=e(ucfirst($u['role']))?></td><td><?=e(formatDate($u['created_at']))?></td></tr><?php endforeach; ?></tbody></table></div></div>
