<?php
// Dashboard dosen/admin: unggah dan kelola contoh dokumen PDF untuk mahasiswa.
// Membutuhkan $myExamples dan $role dari dashboard.php.
?>
<section class="card" id="contoh-dokumen"><div class="section-heading"><span class="eyebrow">PEDOMAN</span><h2>Contoh Dokumen untuk Mahasiswa</h2><p>Unggah contoh dalam format PDF, misalnya proposal lengkap yang tata tulis dan strukturnya sudah baik. Mahasiswa melihatnya di dashboard dan dapat membukanya dalam pratinjau.</p></div>
<details class="meeting-form"><summary class="btn btn-primary btn-small">Unggah Contoh Baru</summary>
<form method="post" enctype="multipart/form-data"><?=csrf_field()?><input type="hidden" name="action" value="upload_example">
<div class="form-grid"><div class="form-group"><label for="example-title">Judul contoh</label><input id="example-title" name="judul" minlength="5" maxlength="200" required placeholder="Contoh: Proposal PTK Motorik Halus (tata tulis lengkap)"></div>
<div class="form-group"><label for="example-category">Jenis</label><select id="example-category" name="kategori" required><?php foreach(EXAMPLE_CATEGORIES as $categoryKey=>$categoryLabel): ?><option value="<?=h($categoryKey)?>"><?=h($categoryLabel)?></option><?php endforeach; ?></select></div></div>
<div class="form-group"><label for="example-note">Keterangan <span class="optional-label">Opsional</span></label><textarea id="example-note" name="keterangan" rows="2" maxlength="500" placeholder="Hal yang perlu diperhatikan mahasiswa dari contoh ini."></textarea></div>
<?php if($role==='dosen'): ?><div class="form-group"><span class="form-label">Dapat dilihat oleh</span><div class="choice-row"><label class="checkbox-line"><input type="radio" name="visibilitas" value="semua" checked> Semua mahasiswa</label><label class="checkbox-line"><input type="radio" name="visibilitas" value="bimbingan"> Hanya mahasiswa bimbingan saya</label></div></div><?php endif; ?>
<div class="form-group"><label for="example-file">File PDF</label><input id="example-file" type="file" name="file_contoh" accept=".pdf,application/pdf" required><small class="field-help">Hanya PDF, maksimal 20 MB. Pastikan identitas pribadi dalam contoh sudah disamarkan bila perlu.</small></div>
<button class="btn btn-primary" type="submit">Unggah Contoh</button></form></details>
<?php if($myExamples): ?><div data-paginate="contoh"><?=paginate_tools('my-example-search','Cari judul atau jenis contoh…','contoh')?><div class="table-wrap"><table><thead><tr><th>Contoh</th><th>Jenis</th><th>Dilihat oleh</th><th>Tindakan</th></tr></thead><tbody>
<?php foreach($myExamples as $example): ?><tr data-paginate-item><td><strong><?=h($example['judul'])?></strong><small class="table-subtext"><?=$role==='admin'?h($example['pengunggah_nama']).' · ':''?><?=h(tanggal_id($example['created_at']))?> · <?=h(examples_size_label((int)$example['ukuran']))?></small></td><td><?=h(EXAMPLE_CATEGORIES[$example['kategori']]??$example['kategori'])?></td><td><?=$example['visibilitas']==='semua'?'Semua mahasiswa':'Mahasiswa bimbingan'?></td><td><div class="table-actions"><button class="btn btn-secondary btn-small" type="button" data-example-open data-src="?action=contoh&amp;id=<?=(int)$example['id']?>" data-title="<?=h($example['judul'])?>">Lihat</button><form method="post" data-confirm-title="Hapus contoh ini?" data-confirm="<?=h($example['judul'])?> tidak lagi tampil bagi mahasiswa." data-confirm-ok="Hapus"><?=csrf_field()?><input type="hidden" name="action" value="delete_example"><input type="hidden" name="contoh_id" value="<?=(int)$example['id']?>"><button class="link-button danger-link" type="submit">Hapus</button></form></div></td></tr><?php endforeach; ?>
</tbody></table></div><?=paginate_footer('contoh')?></div>
<?php else: ?><div class="empty-state"><strong>Belum ada contoh yang Anda unggah.</strong><span>Klik Unggah Contoh Baru untuk menambahkan PDF contoh.</span></div><?php endif; ?>
</section>
