<?php
$user=$_SESSION['user'];
$uid=(int)$user['id'];
$role=$user['role'];
?>
<div class="page-head"><div><h1>Dashboard</h1><p class="muted">Selamat datang, <?=e($user['nama_lengkap'])?>.</p></div><span class="role-badge"><?=e(ucfirst($role))?></span></div>
<div class="card" style="margin-bottom:18px"><strong>Akses cepat</strong><div style="margin-top:10px"><a class="btn btn-secondary" href="?page=konsultasi">Konsultasi</a><?php if($role==='admin'): ?> <a class="btn btn-primary" href="?page=admin-dashboard">Manajemen Admin</a><?php endif; ?></div></div>

<?php if($role==='mahasiswa'): ?>
<?php
$s=$conn->prepare("SELECT id FROM bimbingan WHERE mahasiswa_id=? AND status='aktif' LIMIT 1");
$s->bind_param('i',$uid);$s->execute();$hasActive=$s->get_result()->num_rows>0;$s->close();
?>
<div class="grid-2">
<section class="card"><h2>Ajukan Bimbingan</h2><?php if($hasActive): ?><p class="muted">Anda masih memiliki bimbingan aktif. Pengajuan baru dapat dibuat setelah bimbingan tersebut selesai.</p><?php else: ?><form method="post"><input type="hidden" name="action" value="create_bimbingan"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="form-group"><label>Dosen Pembimbing</label><select name="dosen_id" required><option value="">-- Pilih dosen --</option><?php $r=$conn->query("SELECT id,nama_lengkap FROM users WHERE role='dosen' ORDER BY nama_lengkap"); while($d=$r->fetch_assoc()): ?><option value="<?=$d['id']?>"><?=e($d['nama_lengkap'])?></option><?php endwhile; ?></select></div><div class="form-group"><label>Judul Skripsi</label><input name="judul_skripsi" maxlength="255" required></div><div class="form-group"><label>Deskripsi</label><textarea name="deskripsi" placeholder="Latar belakang atau catatan awal..."></textarea></div><button class="btn btn-primary">Simpan Bimbingan</button></form><?php endif; ?></section>

<section class="card"><h2>Upload Bab</h2><p class="muted">Urutan wajib: Bab 1 → Bab 2 → Bab 3 → Bab 4 → Bab 5. Bab berikutnya hanya dapat diunggah setelah bab sebelumnya ACC.</p><form method="post" enctype="multipart/form-data"><input type="hidden" name="action" value="upload_bab"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="form-group"><label>Bimbingan</label><select name="bimbingan_id" required><option value="">-- Pilih --</option><?php $s=$conn->prepare("SELECT id,judul_skripsi FROM bimbingan WHERE mahasiswa_id=? AND status='aktif' ORDER BY created_at DESC"); $s->bind_param('i',$uid); $s->execute(); $r=$s->get_result(); while($b=$r->fetch_assoc()): ?><option value="<?=$b['id']?>"><?=e($b['judul_skripsi'])?></option><?php endwhile; $s->close(); ?></select></div><div class="form-group"><label>Nama Bab</label><select name="nama_bab" required><option value="">-- Pilih bab --</option><?php for($i=1;$i<=5;$i++): ?><option value="Bab <?=$i?>">Bab <?=$i?></option><?php endfor; ?></select></div><div class="form-group"><label>File (PDF/DOC/DOCX, maks. 10 MB)</label><input type="file" name="file_bab" accept=".pdf,.doc,.docx" required></div><button class="btn btn-success">Upload Bab</button></form></section>
</div>
<section class="card"><h2>Bimbingan Saya</h2><?php $s=$conn->prepare("SELECT b.*,u.nama_lengkap dosen_nama FROM bimbingan b JOIN users u ON u.id=b.dosen_id WHERE b.mahasiswa_id=? ORDER BY b.created_at DESC"); $s->bind_param('i',$uid); $s->execute(); $r=$s->get_result(); if(!$r->num_rows): ?><p class="muted">Belum ada bimbingan.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Judul</th><th>Dosen</th><th>Status</th><th>Detail</th></tr></thead><tbody><?php while($b=$r->fetch_assoc()): ?><tr><td><?=e($b['judul_skripsi'])?></td><td><?=e($b['dosen_nama'])?></td><td><?=getStatusBadge($b['status'])?></td><td><a class="btn btn-secondary" href="?page=bimbingan-detail&id=<?=e($b['id'])?>">Buka</a></td></tr><?php endwhile; ?></tbody></table></div><?php endif; $s->close(); ?></section>

<?php elseif($role==='dosen'): ?>
<section class="card"><h2>Mahasiswa Bimbingan</h2><?php $s=$conn->prepare("SELECT b.*,u.nama_lengkap mahasiswa_nama,u.email FROM bimbingan b JOIN users u ON u.id=b.mahasiswa_id WHERE b.dosen_id=? ORDER BY b.updated_at DESC"); $s->bind_param('i',$uid); $s->execute(); $r=$s->get_result(); if(!$r->num_rows): ?><p class="muted">Belum ada mahasiswa bimbingan.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Mahasiswa</th><th>Judul</th><th>Status</th><th>Detail</th></tr></thead><tbody><?php while($b=$r->fetch_assoc()): ?><tr><td><?=e($b['mahasiswa_nama'])?><br><small><?=e($b['email'])?></small></td><td><?=e($b['judul_skripsi'])?></td><td><?=getStatusBadge($b['status'])?></td><td><a class="btn btn-secondary" href="?page=bimbingan-detail&id=<?=e($b['id'])?>">Buka</a></td></tr><?php endwhile; ?></tbody></table></div><?php endif; $s->close(); ?></section>

<section class="card"><h2>Review Bab & Revisi</h2><p class="muted">Hanya versi terbaru yang sedang menunggu review yang dapat diberi revisi.</p><form method="post"><input type="hidden" name="action" value="add_revision"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="form-group"><label>Bab</label><select name="bab_id" required><option value="">-- Pilih --</option><?php $s=$conn->prepare("SELECT bs.id,bs.nama_bab,bs.versi,u.nama_lengkap FROM bab_skripsi bs JOIN bimbingan b ON b.id=bs.bimbingan_id JOIN users u ON u.id=b.mahasiswa_id WHERE b.dosen_id=? AND b.status='aktif' AND bs.status='menunggu_review' AND bs.id=(SELECT x.id FROM bab_skripsi x WHERE x.bimbingan_id=bs.bimbingan_id AND x.nama_bab=bs.nama_bab ORDER BY x.versi DESC,x.id DESC LIMIT 1) ORDER BY bs.uploaded_at DESC"); $s->bind_param('i',$uid);$s->execute();$r=$s->get_result();while($b=$r->fetch_assoc()): ?><option value="<?=$b['id']?>"><?=e($b['nama_bab'].' v'.$b['versi'].' - '.$b['nama_lengkap'])?></option><?php endwhile;$s->close(); ?></select></div><div class="form-group"><label>Komentar Revisi</label><textarea name="komentar" required></textarea></div><div class="form-group"><label>Tipe Revisi</label><select name="tipe_revisi"><option value="minor">Minor</option><option value="major">Major</option><option value="kritis">Kritis</option></select></div><button class="btn btn-primary">Kirim Revisi</button></form></section>

<section class="card"><h2>Persetujuan Bab</h2><p class="muted">ACC hanya tersedia untuk versi terbaru yang sedang menunggu review.</p><?php $s=$conn->prepare("SELECT bs.id,bs.nama_bab,bs.versi,bs.status,b.id bimbingan_id,u.nama_lengkap FROM bab_skripsi bs JOIN bimbingan b ON b.id=bs.bimbingan_id JOIN users u ON u.id=b.mahasiswa_id WHERE b.dosen_id=? AND b.status='aktif' AND bs.id=(SELECT x.id FROM bab_skripsi x WHERE x.bimbingan_id=bs.bimbingan_id AND x.nama_bab=bs.nama_bab ORDER BY x.versi DESC,x.id DESC LIMIT 1) ORDER BY bs.uploaded_at DESC");$s->bind_param('i',$uid);$s->execute();$r=$s->get_result();if(!$r->num_rows):?><p class="muted">Belum ada bab.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Bab</th><th>Mahasiswa</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php while($b=$r->fetch_assoc()): ?><tr><td><?=e($b['nama_bab'])?> v<?=e($b['versi'])?></td><td><?=e($b['nama_lengkap'])?></td><td><?=getStatusBadge($b['status'])?></td><td><?php if($b['status']==='menunggu_review'): ?><form method="post" class="inline-form"><input type="hidden" name="action" value="approve_bab"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="bab_id" value="<?=e($b['id'])?>"><button class="btn btn-success" type="submit">ACC</button></form><?php elseif($b['status']==='direvisi'): ?>Menunggu revisi mahasiswa<?php elseif($b['status']==='disetujui'): ?>Sudah ACC<?php else: ?>- <?php endif; ?></td></tr><?php endwhile; ?></tbody></table></div><?php endif;$s->close(); ?></section>
<?php endif; ?>
