<section class="hero"><div class="hero-copy"><span class="eyebrow">PLATFORM BIMBINGAN SKRIPSI</span><h1>Selesaikan skripsi dengan alur yang lebih jelas.</h1><p>MyThesis menyatukan dokumen, catatan revisi, dan pemantauan progres dalam satu ruang kerja akademik untuk mahasiswa dan dosen.</p><div class="actions"><?php if(!isset($_SESSION['user'])): ?><a href="?page=register" class="btn btn-primary">Mulai sebagai Mahasiswa</a><a href="?page=login" class="btn btn-secondary">Masuk</a><?php else: ?><a href="?page=dashboard" class="btn btn-primary">Buka Dashboard</a><?php endif; ?></div><div class="hero-trust"><span><strong>01</strong> Progres terpantau</span><span><strong>02</strong> Riwayat tersimpan</span><span><strong>03</strong> Dokumen terorganisasi</span></div></div><aside class="hero-panel" aria-label="Alur bimbingan MyThesis"><span class="hero-panel-label">ALUR TERSTRUKTUR</span><ol><li><span>1</span><div><strong>Buat bimbingan</strong><small>Hubungkan mahasiswa dengan dosen pembimbing.</small></div></li><li><span>2</span><div><strong>Unggah per bab</strong><small>Simpan dokumen sesuai tahap penelitian.</small></div></li><li><span>3</span><div><strong>Tindak lanjuti revisi</strong><small>Catatan dosen tersusun pada setiap naskah.</small></div></li><li><span>4</span><div><strong>Pantau penyelesaian</strong><small>Lihat perkembangan secara berkala.</small></div></li></ol></aside></section>
<?php
$homeLecturers = [];
if (column_exists($conn, 'users', 'tampil_beranda')) {
    $lecturerResult = $conn->query("SELECT id,nama_lengkap FROM users WHERE role='dosen' AND tampil_beranda=1 ORDER BY nama_lengkap");
    $homeLecturers = $lecturerResult ? $lecturerResult->fetch_all(MYSQLI_ASSOC) : [];
}
if ($homeLecturers): ?>
<section class="home-lecturers" aria-labelledby="home-lecturers-title"><div class="section-heading"><span class="eyebrow">DOSEN PEMBIMBING</span><h2 id="home-lecturers-title">Dibimbing oleh dosen yang terdaftar di MyThesis</h2><p>Pilih salah satu dosen berikut sebagai pembimbing saat mendaftar.</p></div><div class="lecturer-grid"><?php foreach($homeLecturers as $lecturer): $photoFile = null; foreach (['jpg','png','webp'] as $extension) { $candidate = __DIR__ . '/../../storage/avatars/user-' . (int)$lecturer['id'] . '.' . $extension; if (is_file($candidate)) { $photoFile = $candidate; break; } } $nameParts = array_slice(array_filter(preg_split('/\s+/', trim(preg_replace('/^(Prof\.?|Dr\.?)\s+/i', '', (string)$lecturer['nama_lengkap'])))), 0, 2); $initials = ''; foreach ($nameParts as $part) $initials .= strtoupper(substr($part, 0, 1)); ?><article class="lecturer-card"><div class="lecturer-photo"><?php if($photoFile): ?><img src="?action=avatar&amp;id=<?=(int)$lecturer['id']?>&amp;v=<?=filemtime($photoFile)?>" alt="Foto <?=h($lecturer['nama_lengkap'])?>" loading="lazy"><?php else: ?><span aria-hidden="true"><?=h($initials ?: 'D')?></span><?php endif; ?></div><h3><?=h($lecturer['nama_lengkap'])?></h3><small>Dosen Pembimbing</small></article><?php endforeach; ?></div></section>
<?php endif; ?>
<section class="section-heading"><span class="eyebrow">FUNGSI UTAMA</span><h2>Satu ruang kerja untuk seluruh proses bimbingan</h2><p>Informasi penting tampil pada waktu yang tepat dan mudah dipahami.</p></section>
<div class="grid-3"><article class="card feature"><div class="feature-icon">01</div><h2>Dokumen terorganisasi</h2><p>Unggah dokumen bab dalam format yang ditentukan dan temukan kembali dengan mudah.</p></article><article class="card feature"><div class="feature-icon">02</div><h2>Revisi mudah ditelusuri</h2><p>Catatan dosen terhubung dengan bab mahasiswa sehingga arahan tidak tercecer.</p></article><article class="card feature"><div class="feature-icon">03</div><h2>Progres terlihat jelas</h2><p>Status bimbingan membantu pengguna menentukan tindakan berikutnya.</p></article></div>
<section class="home-roles"><div><span class="eyebrow">UNTUK MAHASISWA</span><h2>Ketahui langkah berikutnya</h2><p>Kelola dokumen dan pantau status bimbingan dari satu halaman.</p></div><div><span class="eyebrow">UNTUK DOSEN</span><h2>Fokus pada naskah prioritas</h2><p>Lihat mahasiswa bimbingan dan berikan catatan secara lebih teratur.</p></div></section>
