<?php
// Bagian dashboard dosen: log pertemuan yang menunggu konfirmasi dosen ini (seluruh periode dan tab).
// Membutuhkan $pendingMeetings dari dashboard.php.
?>
<section class="card" id="konfirmasi-pertemuan"><div class="section-heading"><span class="eyebrow">PERTEMUAN</span><h2>Konfirmasi Pertemuan Bimbingan</h2><p>Mahasiswa mencatat pertemuan dengan Anda. Konfirmasi bila pertemuan dan arahannya sesuai; pertemuan terkonfirmasi tercetak di kartu bimbingan (target minimal <?=meeting_target()?> pertemuan).</p></div>
<?php if($pendingMeetings): ?><div data-paginate="pertemuan"><?=paginate_tools('pending-meeting-search','Cari nama mahasiswa, tanggal, atau topik…','pertemuan')?><div class="table-wrap"><table class="meeting-table"><thead><tr><th>Mahasiswa</th><th>Tanggal</th><th>Topik dan Arahan</th><th>Tindakan</th></tr></thead><tbody>
<?php foreach($pendingMeetings as $log): $logId=(int)$log['id']; ?><tr data-paginate-item><td><strong><?=h($log['mahasiswa_nama'])?></strong><small class="table-subtext"><?=h($log['judul_skripsi'])?></small></td><td><strong><?=h(tanggal_id($log['tanggal']))?></strong><small class="table-subtext"><?=h(meeting_method_label((string)$log['metode']))?></small></td><td><strong><?=h($log['topik'])?></strong><small class="table-subtext meeting-notes"><?=nl2br(h($log['catatan']))?></small></td><td><div class="table-actions"><form method="post" data-confirm-title="Konfirmasi pertemuan ini?" data-confirm="Pertemuan <?=h($log['mahasiswa_nama'])?> tanggal <?=h(tanggal_id($log['tanggal']))?> akan dihitung dan tercetak di kartu bimbingan." data-confirm-ok="Konfirmasi"><?=csrf_field()?><input type="hidden" name="action" value="confirm_meeting"><input type="hidden" name="log_id" value="<?=$logId?>"><button class="btn btn-success btn-small" type="submit">Konfirmasi</button></form><details class="title-revise"><summary class="btn btn-secondary btn-small">Tolak</summary><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="reject_meeting"><input type="hidden" name="log_id" value="<?=$logId?>"><label for="meeting-reason-<?=$logId?>">Alasan penolakan</label><textarea id="meeting-reason-<?=$logId?>" name="alasan" rows="2" minlength="5" maxlength="500" required placeholder="Contoh: Tanggal tidak sesuai jadwal pertemuan."></textarea><button class="btn btn-primary btn-small" type="submit">Kirim Penolakan</button></form></details></div></td></tr><?php endforeach; ?>
</tbody></table></div><?=paginate_footer('pertemuan')?></div>
<?php else: ?><div class="empty-state"><strong>Tidak ada pertemuan yang menunggu konfirmasi.</strong><span>Log pertemuan baru dari mahasiswa akan tampil di sini.</span></div><?php endif; ?>
</section>
