<?php
// Bagian dashboard dosen: pendaftaran mahasiswa yang menunggu diterima (Pembimbing 1).
// Membutuhkan $pendingRegistrations dari dashboard.php.
?>
<section class="card" id="pendaftaran-baru"><div class="section-heading"><span class="eyebrow">PENDAFTARAN</span><h2>Pendaftaran Mahasiswa Baru</h2><p>Mahasiswa berikut mendaftar dan memilih Anda sebagai Pembimbing 1. Terima bila datanya benar. Tolak bila akun ganda, salah pilih dosen, atau tidak Anda kenal; pendaftaran dan akunnya akan dihapus.</p></div>
<div class="registration-list">
<?php foreach($pendingRegistrations as $registration): $registrationId=(int)$registration['id'];$academicParts=array_filter([$registration['nim']?'NIM '.$registration['nim']:'',$registration['prodi_nama']?trim(($registration['prodi_jenjang']?$registration['prodi_jenjang'].' ':'').$registration['prodi_nama']):'',$registration['angkatan']?'Angkatan '.$registration['angkatan']:'']); ?>
<article class="registration-item">
<div class="registration-main"><strong><?=h($registration['nama_lengkap'])?></strong><?php if($academicParts): ?><small class="table-subtext"><?=h(implode(' · ',$academicParts))?></small><?php endif; ?><small class="table-subtext"><?=h($registration['email'])?><?=!empty($registration['no_telp'])?' · '.h($registration['no_telp']):''?></small><p class="registration-title"><?=h($registration['judul_skripsi'])?></p><small class="table-subtext">Mendaftar <?=h(tanggal_id($registration['created_at'], true))?></small>
<?php if($registration['kemungkinan_ganda']): ?><div class="duplicate-warning" role="note"><strong>Kemungkinan akun ganda</strong><?php foreach($registration['kemungkinan_ganda'] as $other): ?><span><?=h($other['nama_lengkap'])?><?=$other['nim']?' · NIM '.h($other['nim']):' · tanpa NIM'?> · <?=h($other['email'])?><?=$other['dosen_nama']?' · pembimbing: '.h($other['dosen_nama']):' · belum punya bimbingan'?></span><?php endforeach; ?><small>Pastikan dengan mahasiswa akun mana yang dipakai sebelum menerima.</small></div><?php endif; ?>
</div>
<div class="table-actions registration-actions"><form method="post" data-confirm-title="Terima pendaftaran?" data-confirm="<?=h($registration['nama_lengkap'])?> menjadi mahasiswa bimbingan Anda, dan pengajuan judulnya dapat direview." data-confirm-ok="Terima"><?=csrf_field()?><input type="hidden" name="action" value="accept_registration"><input type="hidden" name="bimbingan_id" value="<?=$registrationId?>"><button class="btn btn-success btn-small" type="submit">Terima</button></form>
<details class="title-revise"><summary class="btn btn-secondary btn-small">Tolak &amp; Hapus</summary><form method="post" data-confirm-title="Tolak dan hapus pendaftaran?" data-confirm="Pendaftaran <?=h($registration['nama_lengkap'])?> akan dihapus. Akun mahasiswa ikut dihapus bila tidak memiliki bimbingan lain. Mahasiswa menerima email pemberitahuan. Tindakan ini tidak dapat dibatalkan." data-confirm-ok="Tolak dan hapus"><?=csrf_field()?><input type="hidden" name="action" value="reject_registration"><input type="hidden" name="bimbingan_id" value="<?=$registrationId?>"><label for="reject-reason-<?=$registrationId?>">Alasan <span class="optional-label">Opsional</span></label><textarea id="reject-reason-<?=$registrationId?>" name="alasan" rows="2" maxlength="500" placeholder="Contoh: Akun ganda, gunakan akun dengan NIM."></textarea><button class="btn btn-primary btn-small" type="submit">Tolak dan Hapus</button></form></details></div>
</article>
<?php endforeach; ?>
</div></section>
