<?php
$registerMessage='';$registerType='danger';
if($_SERVER['REQUEST_METHOD']==='POST'){
    $username=trim($_POST['username']??'');$email=trim($_POST['email']??'');$nama=trim($_POST['nama_lengkap']??'');$password=$_POST['password']??'';$confirm=$_POST['confirm_password']??'';$role=$_POST['role']??'mahasiswa';$telp=trim($_POST['no_telp']??'');
    if($username===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||$nama===''||strlen($password)<8){$registerMessage='Lengkapi data dengan benar. Password minimal 8 karakter.';}
    elseif($password!==$confirm){$registerMessage='Konfirmasi password tidak sama.';}
    elseif(!in_array($role,['mahasiswa','dosen'],true)){$registerMessage='Peran akun tidak valid.';}
    else{$stmt=$conn->prepare('SELECT id FROM users WHERE username=? OR email=? LIMIT 1');$stmt->bind_param('ss',$username,$email);$stmt->execute();$exists=$stmt->get_result()->num_rows>0;$stmt->close();if($exists){$registerMessage='Username atau email sudah terdaftar.';}else{$hash=password_hash($password,PASSWORD_DEFAULT);$stmt=$conn->prepare('INSERT INTO users(username,email,password,role,nama_lengkap,no_telp) VALUES(?,?,?,?,?,?)');$stmt->bind_param('ssssss',$username,$email,$hash,$role,$nama,$telp);$ok=$stmt->execute();$stmt->close();$registerMessage=$ok?'Pendaftaran berhasil. Silakan masuk menggunakan akun Anda.':'Pendaftaran belum berhasil. Silakan coba kembali.';$registerType=$ok?'success':'danger';}}
}
?>
<div class="auth-card auth-card-wide card"><span class="eyebrow">PENDAFTARAN PENGGUNA</span><h1>Buat akun MyThesis</h1><p>Lengkapi data berikut untuk memulai proses bimbingan skripsi.</p><?php if($registerMessage!==''): ?><div class="alert alert-<?=$registerType?>" role="alert"><?=htmlspecialchars($registerMessage,ENT_QUOTES,'UTF-8')?><?php if($registerType==='success'): ?> <a href="?page=login">Masuk sekarang</a><?php endif; ?></div><?php endif; ?><form method="post"><fieldset><legend>Data diri</legend><div class="form-grid"><div class="form-group"><label for="nama_lengkap">Nama Lengkap</label><input id="nama_lengkap" name="nama_lengkap" autocomplete="name" required maxlength="150"></div><div class="form-group"><label for="no_telp">No. Telepon</label><input id="no_telp" name="no_telp" type="tel" autocomplete="tel" maxlength="20" placeholder="Contoh: 081234567890"></div></div></fieldset><fieldset><legend>Informasi akun</legend><div class="form-grid"><div class="form-group"><label for="username">Username</label><input id="username" name="username" autocomplete="username" required maxlength="100"></div><div class="form-group"><label for="email">Email aktif</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="100"></div></div><div class="form-group"><label for="role">Peran</label><select id="role" name="role" required><option value="mahasiswa">Mahasiswa</option><option value="dosen">Dosen</option></select></div></fieldset><fieldset><legend>Keamanan akun</legend><div class="form-grid"><div class="form-group"><label for="register_password">Password</label><div class="password-field"><input id="register_password" name="password" type="password" autocomplete="new-password" minlength="8" maxlength="72" required><button type="button" data-password-toggle aria-controls="register_password">Lihat</button></div><small class="field-help">Minimal 8 karakter.</small></div><div class="form-group"><label for="confirm_password">Konfirmasi Password</label><div class="password-field"><input id="confirm_password" name="confirm_password" type="password" autocomplete="new-password" minlength="8" maxlength="72" required><button type="button" data-password-toggle aria-controls="confirm_password">Lihat</button></div></div></div></fieldset><button class="btn btn-primary btn-block" type="submit">Buat Akun</button></form><p class="auth-switch">Sudah punya akun? <a href="?page=login">Masuk ke MyThesis</a></p></div>
