<?php
require_login();require_once __DIR__.'/../controllers/SeminarController.php';
$u=$_SESSION['user'];$uid=(int)$u['id'];$role=$u['role'];$ctrl=new SeminarController($conn);
if($_SERVER['REQUEST_METHOD']==='POST'&&$role==='admin'){
 verify_csrf();$action=$_POST['action']??'';
 if($action==='create_seminar'){
  $bid=(int)($_POST['bimbingan_id']??0);$tipe=$_POST['tipe_seminar']??'';$tanggal=$_POST['tanggal_seminar']??'';$lokasi=trim($_POST['lokasi']??'');$catatan=trim($_POST['catatan']??'');
  $p=[];foreach(['penguji_1','penguji_2','penguji_3'] as $key){$v=(int)($_POST[$key]??0);$p[]=$v?:null;}
  $ok=$ctrl->create($bid,$tipe,$tanggal,$lokasi,$p[0],$p[1],$p[2],$catatan);$b=$ctrl->getBimbingan($bid);
  if($ok&&$b){notify_user($conn,(int)$b['mahasiswa_id'],'jadwal_seminar','Jadwal '.ucfirst($tipe).' telah dibuat.','?page=seminar');notify_user($conn,(int)$b['dosen_id'],'jadwal_seminar','Jadwal '.ucfirst($tipe).' mahasiswa bimbingan Anda telah dibuat.','?page=seminar');}
  flash($ok?'success':'danger',$ok?'Jadwal berhasil dibuat.':'Jadwal gagal dibuat.');redirect('?page=seminar');
 }
 if($action==='update_seminar_status'){$id=(int)($_POST['seminar_id']??0);$status=$_POST['status']??'';$ok=$ctrl->updateStatus($id,$status);flash($ok?'success':'danger',$ok?'Status jadwal diperbarui.':'Status tidak valid.');redirect('?page=seminar');}
}
$items=$ctrl->listForUser($uid,$role);$bimbingan=[];$dosen=[];
if($role==='admin'){
 $r=$conn->query("SELECT b.id,b.judul_skripsi,m.nama_lengkap mahasiswa_nama FROM bimbingan b JOIN users m ON m.id=b.mahasiswa_id WHERE b.status='aktif' ORDER BY m.nama_lengkap");$bimbingan=$r?$r->fetch_all(MYSQLI_ASSOC):[];
 $r=$conn->query("SELECT id,nama_lengkap FROM users WHERE role='dosen' ORDER BY nama_lengkap");$dosen=$r?$r->fetch_all(MYSQLI_ASSOC):[];
}
?>
<div class="page-head"><div><h1>Seminar & Sidang</h1><p class="muted">Jadwal proposal, hasil, dan sidang skripsi.</p></div></div>
<?php if($role==='admin'): ?><section class="card"><h2>Buat Jadwal</h2><form method="post"><input type="hidden" name="action" value="create_seminar"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><div class="grid-2"><div class="form-group"><label>Bimbingan</label><select name="bimbingan_id" required><option value="">-- Pilih mahasiswa --</option><?php foreach($bimbingan as $b): ?><option value="<?=$b['id']?>"><?=e($b['mahasiswa_nama'].' — '.$b['judul_skripsi'])?></option><?php endforeach; ?></select></div><div class="form-group"><label>Jenis</label><select name="tipe_seminar" required><option value="proposal">Seminar Proposal</option><option value="hasil">Seminar Hasil</option><option value="sidang">Sidang</option></select></div><div class="form-group"><label>Tanggal & waktu</label><input type="datetime-local" name="tanggal_seminar" required></div><div class="form-group"><label>Lokasi</label><input name="lokasi" maxlength="150"></div><?php for($i=1;$i<=3;$i++): ?><div class="form-group"><label>Penguji <?=$i?></label><select name="penguji_<?=$i?>"><option value="">-- Tidak ada --</option><?php foreach($dosen as $d): ?><option value="<?=$d['id']?>"><?=e($d['nama_lengkap'])?></option><?php endforeach; ?></select></div><?php endfor; ?><div class="form-group"><label>Catatan</label><textarea name="catatan"></textarea></div></div><button class="btn btn-primary">Simpan Jadwal</button></form></section><?php endif; ?>
<section class="card"><h2>Daftar Jadwal</h2><?php if(!$items): ?><p class="muted">Belum ada jadwal.</p><?php else: ?><div class="table-wrap"><table><thead><tr><th>Jenis</th><th>Mahasiswa</th><th>Tanggal</th><th>Lokasi</th><th>Penguji</th><th>Status</th><?php if($role==='admin'): ?><th>Aksi</th><?php endif; ?></tr></thead><tbody><?php foreach($items as $s): ?><tr><td><?=e(ucfirst($s['tipe_seminar']))?></td><td><?=e($s['mahasiswa_nama'])?><br><small><?=e($s['judul_skripsi'])?></small></td><td><?=e(formatDateTime($s['tanggal_seminar']))?></td><td><?=e($s['lokasi']?:'-')?></td><td><?=e(implode(', ',array_filter([$s['penguji_1']?'Penguji 1':'',$s['penguji_2']?'Penguji 2':'',$s['penguji_3']?'Penguji 3':'']))?:'-')?></td><td><?=getStatusBadge($s['status'])?></td><?php if($role==='admin'): ?><td><form method="post"><input type="hidden" name="action" value="update_seminar_status"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="seminar_id" value="<?=$s['id']?>"><select name="status"><option value="terjadwal" <?=$s['status']==='terjadwal'?'selected':''?>>Terjadwal</option><option value="berlangsung" <?=$s['status']==='berlangsung'?'selected':''?>>Berlangsung</option><option value="selesai" <?=$s['status']==='selesai'?'selected':''?>>Selesai</option><option value="dibatalkan" <?=$s['status']==='dibatalkan'?'selected':''?>>Dibatalkan</option></select><button class="btn btn-secondary" type="submit">Update</button></form></td><?php endif; ?></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
